name: debugging_dartserver_with_flutter_webapp
description: Web server sandbox
version: 10.0.0


environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
   flutter:
      sdk: flutter
   flutter_flavor: ^3.1.1
   flutter_floc: ^0.0.0-dev.9
   flutter_rating_bar: ^4.0.1
   http: ^0.13.5
   mime_type: ^1.0.0

   form_bloc: ^0.30.0
   cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:


  uses-material-design: true